/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseActionForm: typeof import('./src/components/common/BaseActionForm/index.vue')['default']
    BaseInput: typeof import('./src/components/common/FormElements/BaseInput.vue')['default']
    BaseInputNumber: typeof import('./src/components/common/FormElements/BaseInputNumber.vue')['default']
    BaseSelect: typeof import('./src/components/common/FormElements/BaseSelect.vue')['default']
    BaseSwitch: typeof import('./src/components/common/FormElements/BaseSwitch.vue')['default']
    BaseUpload: typeof import('./src/components/common/FormElements/BaseUpload.vue')['default']
    Button: typeof import('./src/components/common/HoverButton/Button.vue')['default']
    DataTableBase: typeof import('./src/components/common/DataTableBase/index.vue')['default']
    HoverButton: typeof import('./src/components/common/HoverButton/index.vue')['default']
    LanguageSelect: typeof import('./src/components/common/LanguageSelect/index.vue')['default']
    LoadingIcon: typeof import('./src/components/common/LoadingIcon/index.vue')['default']
    LogoApp: typeof import('./src/components/common/LogoApp/index.vue')['default']
    MainHeader: typeof import('./src/components/common/MainHeader/index.vue')['default']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItemGi: typeof import('naive-ui')['NFormItemGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NH1: typeof import('naive-ui')['NH1']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayouteader: typeof import('naive-ui')['NLayouteader']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutooter: typeof import('naive-ui')['NLayoutooter']
    NPopselect: typeof import('naive-ui')['NPopselect']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/common/SvgIcon/index.vue')['default']
    TypeText: typeof import('./src/components/common/TypeText.vue')['default']
  }
}
