
export const initializeModel = (): API.ReportModel => ({
  region: 'الباحة',
  college: 'الكلية التقنية بجدة',
  reportType: 'achievement',
  semester: 'الفصل التدريبي الأول ١٤٤٦',
  executionDate: Date.now().toString(),
  institution: 'عمادة الكلية',
  topic: 'jhj`',
  supervisor: 'jhj',
  resources: 'بشرية فقط',
  operationalGoal: 'jhj',
  executionProcedures: 'jhj',
  challenges: 'jhj',
  recommendations: 'jhj',
  documentation1: null,
  documentation2: null,
  documentation3: null,
  documentation4: null,
  performanceIndicator: '',
  target: 0,
  achieved: 0,
  percentage: '',
  reporter: '',
  reportDate: new Date().toISOString().split('T')[0],
  approver: '',
  stamp: null,
  generalGoal: ' dd',
  mainSupervisor: 'ww',
  subSupervisor: 'dd',
  auditDate: new Date().toISOString().split('T')[0],
  maintenanceType: '',
  maintenanceDate: '',
  maintenanceTime: '',
  requestType: '',
  maintenanceTopic: '',
  faultDescription: '',
  department: '',




  // Added fields
  revenueAmount1: '0.00',
  expenseAmount1: '0.00',
  remainingAmount1: '0.00',
  percentage1: '0.00%',
  revenueType2: '',
  revenueAmount2: '0.00',
  expenseAmount2: '0.00',
  remainingAmount2: '0.00',
  percentage2: '0.00%',
  revenueType3: '',
  revenueAmount3: '0.00',
  expenseAmount3: '0.00',
  remainingAmount3: '0.00',
  percentage3: '0.00%',
  revenueType4: '',
  revenueAmount4: '0.00',
  expenseAmount4: '0.00',
  remainingAmount4: '0.00',
  percentage4: '0.00%',
  revenueType5: '',
  revenueAmount5: '0.00',
  expenseAmount5: '0.00',
  remainingAmount5: '0.00',
  percentage5: '0.00%',
  revenueType6: '',
  revenueAmount6: '0.00',
  expenseAmount6: '0.00',
  remainingAmount6: '0.00',
  percentage6: '0.00%',
  revenueType7: '',
  revenueAmount7: '0.00',
  expenseAmount7: '0.00',
  remainingAmount7: '0.00',
  percentage7: '0.00%',
  revenueType8: '',
  revenueAmount8: '0.00',
  expenseAmount8: '0.00',
  remainingAmount8: '0.00',
  percentage8: '0.00%',
  totalRevenue: '0.00',
  totalExpenses: '0.00',
  totalRemaining: '0.00',
  totalPercentage: '0.00%',
  revenueType1: "",
  email:"",
});