export const initializeModel1 = (): API.ReportModel => ({
  region: 'الباحة',
  college: 'الكلية التقنية بجدة',
  reportType: 'achievement',
  semester: 'الفصل التدريبي الأول ١٤٤٦',
  executionDate: Date.now().toString(),
  institution: 'عمادة الكلية',
  topic: '',
  supervisor: '',
  resources: 'بشرية فقط',
  operationalGoal: '',
  executionProcedures: '',
  challenges: '',
  recommendations: '',
  documentation1: null,
  documentation2: null,
  documentation3: null,
  documentation4: '',
  performanceIndicator: '',
  target: 0,
  achieved: 0,
  percentage: '',
  reporter: '',
  reportDate: new Date().toISOString().split('T')[0],
  approver: '',
  stamp: null,
  generalGoal: '',
  mainSupervisor: '',
  subSupervisor: '',
  auditDate: new Date().toISOString().split('T')[0],
  maintenanceType: '',
  maintenanceDate: '',
  maintenanceTime: '',
  requestType: '',
  maintenanceTopic: '',
  faultDescription: '',
  department: '',




  // Added fields
  revenueAmount1: '0.00',
  expenseAmount1: '0.00',
  remainingAmount1: '0.00',
  percentage1: '0.00%',
  revenueType2: '',
  revenueAmount2: '0.00',
  expenseAmount2: '0.00',
  remainingAmount2: '0.00',
  percentage2: '0.00%',
  revenueType3: '',
  revenueAmount3: '0.00',
  expenseAmount3: '0.00',
  remainingAmount3: '0.00',
  percentage3: '0.00%',
  revenueType4: '',
  revenueAmount4: '0.00',
  expenseAmount4: '0.00',
  remainingAmount4: '0.00',
  percentage4: '0.00%',
  revenueType5: '',
  revenueAmount5: '0.00',
  expenseAmount5: '0.00',
  remainingAmount5: '0.00',
  percentage5: '0.00%',
  revenueType6: '',
  revenueAmount6: '0.00',
  expenseAmount6: '0.00',
  remainingAmount6: '0.00',
  percentage6: '0.00%',
  revenueType7: '',
  revenueAmount7: '0.00',
  expenseAmount7: '0.00',
  remainingAmount7: '0.00',
  percentage7: '0.00%',
  revenueType8: '',
  revenueAmount8: '0.00',
  expenseAmount8: '0.00',
  remainingAmount8: '0.00',
  percentage8: '0.00%',
  totalRevenue: '0.00',
  totalExpenses: '0.00',
  totalRemaining: '0.00',
  totalPercentage: '0.00%',
  revenueType1: "",
  email:"",
});

export const initializeModel = (): API.ReportModel => ({
  region: 'الباحة',
  college: 'الكلية التقنية بجدة',
  reportType: 'achievement',
  semester: 'الفصل التدريبي الأول ١٤٤٦',
  executionDate: new Date().toISOString(),
  institution: 'عمادة الكلية',
  topic: 'تطوير نظام إدارة التقارير',
  supervisor: 'د. محمد أحمد',
  resources: 'بشرية ومادية',
  operationalGoal: 'تحسين كفاءة العمل الإداري وتسريع عملية إعداد التقارير',
  executionProcedures: 'تم تطوير نظام إلكتروني متكامل لإدارة وإعداد التقارير بشكل آلي',
  challenges: 'تحديات في تدريب الموظفين على النظام الجديد',
  recommendations: 'عقد ورش عمل تدريبية إضافية للموظفين',
  documentation1: null,
  documentation2: null,
  documentation3: null,
  documentation4: '',
  performanceIndicator: 'نسبة رضا المستخدمين عن النظام',
  target: 90,
  achieved: 85,
  percentage: '94%',
  reporter: 'أحمد محمد',
  reportDate: new Date().toISOString().split('T')[0],
  approver: 'د. خالد العمري',
  stamp: null,
  generalGoal: 'رفع كفاءة العمليات الإدارية في الكلية',
  mainSupervisor: 'د. عبدالله السعيد',
  subSupervisor: 'م. فيصل الحربي',
  auditDate: new Date().toISOString().split('T')[0],
  maintenanceType: 'صيانة دورية',
  maintenanceDate: new Date().toISOString().split('T')[0],
  maintenanceTime: new Date().toISOString(),
  requestType: 'طلب صيانة عاجل',
  maintenanceTopic: 'صيانة أجهزة المعمل',
  faultDescription: 'عطل في نظام التبريد',
  department: 'قسم تقنية المعلومات',
  email: 'user@example.com',

  // Financial data with realistic values
  revenueType1: 'إيرادات التدريب',
  revenueAmount1: '150000.00',
  expenseAmount1: '75000.00',
  remainingAmount1: '75000.00',
  percentage1: '50.00%',
  
  revenueType2: 'إيرادات الاستشارات',
  revenueAmount2: '100000.00',
  expenseAmount2: '40000.00',
  remainingAmount2: '60000.00',
  percentage2: '60.00%',
  
  revenueType3: 'إيرادات المشاريع',
  revenueAmount3: '200000.00',
  expenseAmount3: '160000.00',
  remainingAmount3: '40000.00',
  percentage3: '20.00%',
  
  revenueType4: 'إيرادات الخدمات',
  revenueAmount4: '80000.00',
  expenseAmount4: '30000.00',
  remainingAmount4: '50000.00',
  percentage4: '62.50%',
  
  revenueType5: 'إيرادات البرامج',
  revenueAmount5: '120000.00',
  expenseAmount5: '90000.00',
  remainingAmount5: '30000.00',
  percentage5: '25.00%',
  
  revenueType6: 'إيرادات المعامل',
  revenueAmount6: '90000.00',
  expenseAmount6: '45000.00',
  remainingAmount6: '45000.00',
  percentage6: '50.00%',
  
  revenueType7: 'إيرادات البحوث',
  revenueAmount7: '175000.00',
  expenseAmount7: '125000.00',
  remainingAmount7: '50000.00',
  percentage7: '28.57%',
  
  revenueType8: 'إيرادات أخرى',
  revenueAmount8: '60000.00',
  expenseAmount8: '20000.00',
  remainingAmount8: '40000.00',
  percentage8: '66.67%',
  
  totalRevenue: '975000.00',
  totalExpenses: '585000.00',
  totalRemaining: '390000.00',
  totalPercentage: '40.00%'
});