
export const initializeModel = (): API.ReportModel => ({
    region: 'الباحة',
    college: 'الكلية التقنية بجدة',
    reportType: 'achievement',
    semester: 'الفصل التدريبي الأول ١٤٤٦',
    executionDate: Date.now().toString(),
    institution: 'عمادة الكلية',
    topic: '',
    supervisor: '',
    resources: 'بشرية فقط',
    operationalGoal: '',
    executionProcedures: '',
    challenges: '',
    recommendations: '',
    documentation1: null,
    documentation2: null,
    documentation3: null,
    documentation4: null,
    performanceIndicator: '',
    target: 0,
    achieved: 0,
    percentage: '',
    reporter: '',
    reportDate: new Date().toISOString().split('T')[0],
    approver: '',
    stamp: null,
    generalGoal: '',
    mainSupervisor: '',
    subSupervisor: '',
    auditDate: new Date().toISOString().split('T')[0],
    maintenanceType: '',
    maintenanceDate: '',
    maintenanceTime: '',
    requestType: '',
    maintenanceTopic: '',
    faultDescription: '',
    department: '',
  });